// <auto-generated />
namespace SmartLogistic.Infrastructure.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class change_type_data_int_in_lat_and_lng_to_double : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(change_type_data_int_in_lat_and_lng_to_double));
        
        string IMigrationMetadata.Id
        {
            get { return "201911241403484_change_type_data_int_in_lat_and_lng_to_double"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
