// <auto-generated />
namespace SmartLogistic.Infrastructure.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class rename_table_map_to_mapLocation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(rename_table_map_to_mapLocation));
        
        string IMigrationMetadata.Id
        {
            get { return "201911240854086_rename_table_map_to_mapLocation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
